import "dotenv/config";

import { PrismaPg } from "@prisma/adapter-pg";

import { PrismaClient } from "../lib/generated/prisma/client";

const connectionString = process.env.DATABASE_URL;

if (!connectionString) {
  throw new Error("DATABASE_URL is required to run the Prisma seed.");
}

const adapter = new PrismaPg({ connectionString });
const prisma = new PrismaClient({ adapter });

const fishSpecies = [
  {
    slug: "guppy",
    commonName: "Guppy",
    scientificName: "Poecilia reticulata",
    temperament: "Paisible",
    behavior: "Paisible et actif",
    swimmingZone: "Surface et milieu",
    diet: "Omnivore",
    minTankLiters: 60,
    minTemperatureC: "22.0",
    maxTemperatureC: "28.0",
    minPh: "6.8",
    maxPh: "7.8",
    minGh: 8,
    maxGh: 20,
    adultSizeCm: "5.00",
    careLevel: "Debutant",
    difficulty: "Debutant",
    minGroupSize: 6,
    lifeExpectancyYears: "2.0",
    shrimpCompatibility: "Avec prudence",
    plantCompatibility: "Compatible",
    notes: "Poisson vif et prolifique. Prevoir un bon ratio femelles/males.",
  },
  {
    slug: "neon-bleu",
    commonName: "Neon bleu",
    scientificName: "Paracheirodon innesi",
    temperament: "Paisible",
    behavior: "Banc paisible",
    swimmingZone: "Milieu",
    diet: "Omnivore",
    minTankLiters: 80,
    minTemperatureC: "20.0",
    maxTemperatureC: "26.0",
    minPh: "6.0",
    maxPh: "7.2",
    minGh: 2,
    maxGh: 10,
    adultSizeCm: "4.00",
    careLevel: "Debutant",
    difficulty: "Debutant",
    minGroupSize: 10,
    lifeExpectancyYears: "5.0",
    shrimpCompatibility: "Avec prudence",
    plantCompatibility: "Compatible",
    notes: "Prefere une eau douce et un groupe nombreux.",
  },
  {
    slug: "corydoras",
    commonName: "Corydoras",
    scientificName: "Corydoras",
    temperament: "Paisible",
    behavior: "Gregaire et fouisseur leger",
    swimmingZone: "Fond",
    diet: "Omnivore de fond",
    minTankLiters: 80,
    minTemperatureC: "22.0",
    maxTemperatureC: "26.0",
    minPh: "6.0",
    maxPh: "7.5",
    minGh: 2,
    maxGh: 15,
    adultSizeCm: "6.00",
    careLevel: "Debutant",
    difficulty: "Debutant",
    minGroupSize: 6,
    lifeExpectancyYears: "6.0",
    shrimpCompatibility: "Compatible",
    plantCompatibility: "Compatible",
    notes: "Demande un sol non coupant pour proteger les barbillons.",
  },
  {
    slug: "betta-splendens",
    commonName: "Betta splendens",
    scientificName: "Betta splendens",
    temperament: "Territorial",
    behavior: "Territorial, surtout entre males",
    swimmingZone: "Surface et milieu",
    diet: "Carnivore",
    minTankLiters: 30,
    minTemperatureC: "24.0",
    maxTemperatureC: "28.0",
    minPh: "6.5",
    maxPh: "7.5",
    minGh: 3,
    maxGh: 12,
    adultSizeCm: "7.00",
    careLevel: "Intermediaire",
    difficulty: "Intermediaire",
    minGroupSize: 1,
    lifeExpectancyYears: "3.0",
    shrimpCompatibility: "Avec prudence",
    plantCompatibility: "Compatible",
    notes: "A maintenir seul ou avec une population choisie tres prudemment.",
  },
  {
    slug: "platy",
    commonName: "Platy",
    scientificName: "Xiphophorus maculatus",
    temperament: "Paisible",
    behavior: "Actif et paisible",
    swimmingZone: "Milieu",
    diet: "Omnivore",
    minTankLiters: 80,
    minTemperatureC: "20.0",
    maxTemperatureC: "26.0",
    minPh: "7.0",
    maxPh: "8.2",
    minGh: 10,
    maxGh: 25,
    adultSizeCm: "6.00",
    careLevel: "Debutant",
    difficulty: "Debutant",
    minGroupSize: 5,
    lifeExpectancyYears: "3.0",
    shrimpCompatibility: "Avec prudence",
    plantCompatibility: "Compatible",
    notes: "Apprecie une eau plutot dure et basique.",
  },
  {
    slug: "molly",
    commonName: "Molly",
    scientificName: "Poecilia sphenops",
    temperament: "Paisible",
    behavior: "Actif, parfois insistant",
    swimmingZone: "Milieu et surface",
    diet: "Omnivore",
    minTankLiters: 100,
    minTemperatureC: "24.0",
    maxTemperatureC: "28.0",
    minPh: "7.2",
    maxPh: "8.2",
    minGh: 12,
    maxGh: 30,
    adultSizeCm: "8.00",
    careLevel: "Debutant",
    difficulty: "Debutant",
    minGroupSize: 5,
    lifeExpectancyYears: "4.0",
    shrimpCompatibility: "Avec prudence",
    plantCompatibility: "Compatible",
    notes: "Demande un bac stable et une eau mineralisee.",
  },
  {
    slug: "ancistrus",
    commonName: "Ancistrus",
    scientificName: "Ancistrus",
    temperament: "Paisible",
    behavior: "Calme, territorial avec ses caches",
    swimmingZone: "Fond et decor",
    diet: "Herbivore",
    minTankLiters: 120,
    minTemperatureC: "23.0",
    maxTemperatureC: "27.0",
    minPh: "6.0",
    maxPh: "7.5",
    minGh: 3,
    maxGh: 15,
    adultSizeCm: "12.00",
    careLevel: "Intermediaire",
    difficulty: "Intermediaire",
    minGroupSize: 1,
    lifeExpectancyYears: "8.0",
    shrimpCompatibility: "Compatible",
    plantCompatibility: "Avec prudence",
    notes: "Prevoir racines, cachettes et apport vegetal regulier.",
  },
  {
    slug: "danio-rerio",
    commonName: "Danio rerio",
    scientificName: "Danio rerio",
    temperament: "Actif",
    behavior: "Tres actif, gregaire",
    swimmingZone: "Surface et milieu",
    diet: "Omnivore",
    minTankLiters: 80,
    minTemperatureC: "18.0",
    maxTemperatureC: "26.0",
    minPh: "6.5",
    maxPh: "7.8",
    minGh: 5,
    maxGh: 20,
    adultSizeCm: "5.00",
    careLevel: "Debutant",
    difficulty: "Debutant",
    minGroupSize: 8,
    lifeExpectancyYears: "4.0",
    shrimpCompatibility: "Avec prudence",
    plantCompatibility: "Compatible",
    notes: "Aime une bonne longueur de nage et une eau bien oxygenee.",
  },
  {
    slug: "rasbora-arlequin",
    commonName: "Rasbora arlequin",
    scientificName: "Trigonostigma heteromorpha",
    temperament: "Paisible",
    behavior: "Banc calme et paisible",
    swimmingZone: "Milieu",
    diet: "Omnivore",
    minTankLiters: 80,
    minTemperatureC: "23.0",
    maxTemperatureC: "28.0",
    minPh: "6.0",
    maxPh: "7.5",
    minGh: 2,
    maxGh: 12,
    adultSizeCm: "4.50",
    careLevel: "Debutant",
    difficulty: "Debutant",
    minGroupSize: 8,
    lifeExpectancyYears: "5.0",
    shrimpCompatibility: "Avec prudence",
    plantCompatibility: "Compatible",
    notes: "Mis en valeur dans un bac plante avec zones ombragees.",
  },
  {
    slug: "gourami-nain",
    commonName: "Gourami nain",
    scientificName: "Trichogaster lalius",
    temperament: "Calme",
    behavior: "Calme, parfois territorial en surface",
    swimmingZone: "Surface et milieu",
    diet: "Omnivore",
    minTankLiters: 80,
    minTemperatureC: "24.0",
    maxTemperatureC: "28.0",
    minPh: "6.0",
    maxPh: "7.5",
    minGh: 3,
    maxGh: 15,
    adultSizeCm: "6.00",
    careLevel: "Intermediaire",
    difficulty: "Intermediaire",
    minGroupSize: 1,
    lifeExpectancyYears: "4.0",
    shrimpCompatibility: "Avec prudence",
    plantCompatibility: "Compatible",
    notes: "Apprecie les plantes flottantes et les zones calmes.",
  },
];

const plantSpecies = [
  {
    slug: "anubias",
    commonName: "Anubias",
    scientificName: "Anubias",
    growthRate: "Lente",
    lightNeed: "Faible",
    co2Need: "Optionnel",
    fertilizerNeed: "Faible",
    placement: "Avant-plan ou decor",
    minTemperatureC: "20.0",
    maxTemperatureC: "28.0",
    minPh: "6.0",
    maxPh: "7.8",
    careLevel: "Debutant",
    difficulty: "Debutant",
    trimmingEveryDays: 90,
    notes: "Plante robuste a fixer sur racine ou pierre, rhizome hors substrat.",
  },
  {
    slug: "fougere-de-java",
    commonName: "Fougere de Java",
    scientificName: "Microsorum pteropus",
    growthRate: "Lente",
    lightNeed: "Faible",
    co2Need: "Optionnel",
    fertilizerNeed: "Faible",
    placement: "Decor",
    minTemperatureC: "20.0",
    maxTemperatureC: "28.0",
    minPh: "6.0",
    maxPh: "7.8",
    careLevel: "Debutant",
    difficulty: "Debutant",
    trimmingEveryDays: 90,
    notes: "Rhizome a fixer sur support, croissance lente et tres tolerante.",
  },
  {
    slug: "vallisneria",
    commonName: "Vallisneria",
    scientificName: "Vallisneria",
    growthRate: "Rapide",
    lightNeed: "Moyen",
    co2Need: "Optionnel",
    fertilizerNeed: "Moyen",
    placement: "Arriere-plan",
    minTemperatureC: "20.0",
    maxTemperatureC: "28.0",
    minPh: "6.5",
    maxPh: "8.0",
    careLevel: "Debutant",
    difficulty: "Debutant",
    trimmingEveryDays: 30,
    notes: "Bonne plante d'arriere-plan, se propage par stolons.",
  },
  {
    slug: "cryptocoryne",
    commonName: "Cryptocoryne",
    scientificName: "Cryptocoryne",
    growthRate: "Moyenne",
    lightNeed: "Faible a moyen",
    co2Need: "Optionnel",
    fertilizerNeed: "Moyen",
    placement: "Milieu",
    minTemperatureC: "22.0",
    maxTemperatureC: "28.0",
    minPh: "6.0",
    maxPh: "7.8",
    careLevel: "Debutant",
    difficulty: "Debutant",
    trimmingEveryDays: 60,
    notes: "Peut fondre apres plantation puis repartir si les racines restent saines.",
  },
  {
    slug: "egeria-densa",
    commonName: "Egeria densa",
    scientificName: "Egeria densa",
    growthRate: "Rapide",
    lightNeed: "Moyen",
    co2Need: "Optionnel",
    fertilizerNeed: "Moyen",
    placement: "Arriere-plan",
    minTemperatureC: "18.0",
    maxTemperatureC: "26.0",
    minPh: "6.5",
    maxPh: "8.0",
    careLevel: "Debutant",
    difficulty: "Debutant",
    trimmingEveryDays: 14,
    notes: "Tige rapide utile pour consommer les nitrates et densifier le fond.",
  },
  {
    slug: "hygrophila-polysperma",
    commonName: "Hygrophila polysperma",
    scientificName: "Hygrophila polysperma",
    growthRate: "Rapide",
    lightNeed: "Moyen",
    co2Need: "Optionnel",
    fertilizerNeed: "Moyen a fort",
    placement: "Milieu ou arriere-plan",
    minTemperatureC: "20.0",
    maxTemperatureC: "28.0",
    minPh: "6.0",
    maxPh: "8.0",
    careLevel: "Debutant",
    difficulty: "Debutant",
    trimmingEveryDays: 21,
    notes: "Tige robuste, pousse vite et supporte bien les tailles regulieres.",
  },
  {
    slug: "bucephalandra",
    commonName: "Bucephalandra",
    scientificName: "Bucephalandra",
    growthRate: "Lente",
    lightNeed: "Faible a moyen",
    co2Need: "Optionnel",
    fertilizerNeed: "Faible a moyen",
    placement: "Decor",
    minTemperatureC: "20.0",
    maxTemperatureC: "28.0",
    minPh: "5.5",
    maxPh: "7.5",
    careLevel: "Intermediaire",
    difficulty: "Intermediaire",
    trimmingEveryDays: 120,
    notes: "Plante lente a fixer sur support, sensible aux changements brusques.",
  },
  {
    slug: "mousse-de-java",
    commonName: "Mousse de Java",
    scientificName: "Taxiphyllum barbieri",
    growthRate: "Moyenne",
    lightNeed: "Faible",
    co2Need: "Optionnel",
    fertilizerNeed: "Faible",
    placement: "Decor ou avant-plan",
    minTemperatureC: "18.0",
    maxTemperatureC: "28.0",
    minPh: "6.0",
    maxPh: "7.8",
    careLevel: "Debutant",
    difficulty: "Debutant",
    trimmingEveryDays: 45,
    notes: "Mousse polyvalente pour decor, cachettes et supports de microfaune.",
  },
  {
    slug: "ludwigia-repens",
    commonName: "Ludwigia repens",
    scientificName: "Ludwigia repens",
    growthRate: "Rapide",
    lightNeed: "Moyen a fort",
    co2Need: "Utile",
    fertilizerNeed: "Moyen a fort",
    placement: "Milieu ou arriere-plan",
    minTemperatureC: "20.0",
    maxTemperatureC: "28.0",
    minPh: "6.0",
    maxPh: "7.5",
    careLevel: "Intermediaire",
    difficulty: "Intermediaire",
    trimmingEveryDays: 21,
    notes: "Couleur rouge favorisee par une bonne lumiere et une fertilisation stable.",
  },
  {
    slug: "rotala-rotundifolia",
    commonName: "Rotala rotundifolia",
    scientificName: "Rotala rotundifolia",
    growthRate: "Rapide",
    lightNeed: "Moyen a fort",
    co2Need: "Utile",
    fertilizerNeed: "Moyen a fort",
    placement: "Arriere-plan",
    minTemperatureC: "20.0",
    maxTemperatureC: "28.0",
    minPh: "5.5",
    maxPh: "7.5",
    careLevel: "Intermediaire",
    difficulty: "Intermediaire",
    trimmingEveryDays: 14,
    notes: "Tige fine ideale en massif, demande taille et nutrition regulieres.",
  },
];

async function main() {
  await prisma.$transaction([
    ...fishSpecies.map((species) =>
      prisma.fishSpecies.upsert({
        where: { slug: species.slug },
        update: {
          ...species,
          isPublic: true,
        },
        create: {
          ...species,
          isPublic: true,
        },
      })
    ),
    ...plantSpecies.map((species) =>
      prisma.plantSpecies.upsert({
        where: { slug: species.slug },
        update: {
          ...species,
          isPublic: true,
        },
        create: {
          ...species,
          isPublic: true,
        },
      })
    ),
  ]);
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (error) => {
    console.error(error);
    await prisma.$disconnect();
    process.exit(1);
  });
