import { requireUser } from "@/lib/auth/session";
import { prisma } from "@/lib/prisma";
import {
  alertSeverityToPriority,
  getAlertSeverityLabel,
  type AlertSeverityValue,
} from "@/rules/alert";
import type { ReminderTypeValue } from "@/rules/reminder";

type DecimalLike = {
  toString(): string;
};

type AlertSuggestion = {
  fingerprint: string;
  type: AlertTypeValue;
  severity: AlertSeverityValue;
  title: string;
  message: string;
  probableCause: string;
  recommendedAction: string;
  recommendedDelay: string;
  reminder?: {
    type: ReminderTypeValue;
    title: string;
    description: string;
    dueInDays: number;
    repeatEveryDays?: number;
  };
};

type AlertTypeValue =
  | "WATER_PARAMETER"
  | "MAINTENANCE_OVERDUE"
  | "FEEDING_MISSED"
  | "FEEDING"
  | "EQUIPMENT"
  | "FISH_HEALTH"
  | "PLANT_HEALTH"
  | "SYSTEM"
  | "CUSTOM";

type RawAlert = {
  id: string;
  type: string;
  title: string;
  message: string;
  severity: string;
  priority: string;
  fingerprint: string | null;
  probableCause: string | null;
  recommendedAction: string | null;
  recommendedDelay: string | null;
  status: string;
  triggeredAt: Date;
  resolvedAt: Date | null;
  createdAt: Date;
};

export type AlertEntry = {
  id: string;
  type: string;
  title: string;
  message: string;
  severity: string;
  severityLabel: string;
  priority: string;
  fingerprint: string | null;
  probableCause: string;
  recommendedAction: string;
  recommendedDelay: string;
  status: string;
  triggeredAt: string;
  triggeredAtLabel: string;
  resolvedAt: string | null;
};

export type AquariumAlertAnalysisResult = {
  created: number;
  updated: number;
  activeCount: number;
  recommendationCount: number;
};

const alertSelect = {
  id: true,
  type: true,
  title: true,
  message: true,
  severity: true,
  priority: true,
  fingerprint: true,
  probableCause: true,
  recommendedAction: true,
  recommendedDelay: true,
  status: true,
  triggeredAt: true,
  resolvedAt: true,
  createdAt: true,
} as const;

function decimalToNumber(value: DecimalLike | null | undefined) {
  if (!value) {
    return null;
  }

  const numberValue = Number(value.toString());

  return Number.isFinite(numberValue) ? numberValue : null;
}

function daysSince(date: Date | null | undefined) {
  if (!date) {
    return null;
  }

  return Math.floor((Date.now() - date.getTime()) / (24 * 60 * 60 * 1000));
}

function dueDateIn(days: number) {
  const date = new Date();
  date.setDate(date.getDate() + days);
  date.setHours(9, 0, 0, 0);
  return date;
}

function latestDateByType(
  logs: { type: string; performedAt: Date }[],
  type: string
) {
  return logs.find((log) => log.type === type)?.performedAt ?? null;
}

function toAlertEntry(alert: RawAlert): AlertEntry {
  return {
    id: alert.id,
    type: alert.type,
    title: alert.title,
    message: alert.message,
    severity: alert.severity,
    severityLabel: getAlertSeverityLabel(alert.severity),
    priority: alert.priority,
    fingerprint: alert.fingerprint,
    probableCause: alert.probableCause ?? "Non renseignee",
    recommendedAction: alert.recommendedAction ?? "Aucune action renseignee.",
    recommendedDelay: alert.recommendedDelay ?? "Non renseigne",
    status: alert.status,
    triggeredAt: alert.triggeredAt.toISOString(),
    triggeredAtLabel: alert.triggeredAt.toLocaleDateString("fr-FR", {
      dateStyle: "medium",
    }),
    resolvedAt: alert.resolvedAt?.toISOString() ?? null,
  };
}

function getRangeProblem(
  actual: number | null,
  ranges: { min: number | null; max: number | null; name: string }[]
) {
  if (actual === null || ranges.length === 0) {
    return null;
  }

  const tooLowFor = ranges.filter((range) => range.min !== null && actual < range.min);
  const tooHighFor = ranges.filter((range) => range.max !== null && actual > range.max);

  if (tooLowFor.length === 0 && tooHighFor.length === 0) {
    return null;
  }

  const impacted = [...tooLowFor, ...tooHighFor]
    .slice(0, 4)
    .map((range) => range.name)
    .join(", ");
  const direction = tooLowFor.length > 0 ? "trop basse" : "trop elevee";

  return {
    direction,
    impacted,
  };
}

async function ensureReminder(
  userId: string,
  aquariumId: string,
  suggestion: NonNullable<AlertSuggestion["reminder"]>
) {
  const existingReminder = await prisma.reminder.findFirst({
    where: {
      userId,
      aquariumId,
      type: suggestion.type,
      status: {
        in: ["PENDING", "SNOOZED"],
      },
      isAutoGenerated: true,
      isAutoEnabled: true,
    },
    select: {
      id: true,
      dueAt: true,
    },
  });

  const dueAt = dueDateIn(suggestion.dueInDays);

  if (existingReminder) {
    if (existingReminder.dueAt > dueAt) {
      await prisma.reminder.update({
        where: {
          id: existingReminder.id,
        },
        data: {
          dueAt,
          title: suggestion.title,
          description: suggestion.description,
        },
      });
    }

    return;
  }

  await prisma.reminder.create({
    data: {
      userId,
      aquariumId,
      type: suggestion.type,
      title: suggestion.title,
      description: suggestion.description,
      dueAt,
      repeatEveryDays: suggestion.repeatEveryDays,
      priority: "HIGH",
      status: "PENDING",
      isAutoGenerated: true,
      isAutoEnabled: true,
    },
  });
}

async function upsertAlertSuggestion(
  userId: string,
  aquariumId: string,
  suggestion: AlertSuggestion
) {
  const existingAlert = await prisma.alert.findFirst({
    where: {
      userId,
      aquariumId,
      fingerprint: suggestion.fingerprint,
      status: {
        in: ["OPEN", "ACKNOWLEDGED"],
      },
    },
    select: {
      id: true,
    },
  });

  const data = {
    type: suggestion.type,
    title: suggestion.title,
    message: suggestion.message,
    severity: suggestion.severity,
    priority: alertSeverityToPriority(suggestion.severity),
    fingerprint: suggestion.fingerprint,
    probableCause: suggestion.probableCause,
    recommendedAction: suggestion.recommendedAction,
    recommendedDelay: suggestion.recommendedDelay,
    status: "OPEN" as const,
    resolvedAt: null,
  };

  if (existingAlert) {
    await prisma.alert.update({
      where: {
        id: existingAlert.id,
      },
      data,
    });

    return "updated" as const;
  }

  await prisma.alert.create({
    data: {
      userId,
      aquariumId,
      ...data,
    },
  });

  return "created" as const;
}

async function upsertRecommendation(
  userId: string,
  aquariumId: string,
  suggestion: AlertSuggestion
) {
  const existingRecommendation = await prisma.aiRecommendation.findFirst({
    where: {
      userId,
      aquariumId,
      title: suggestion.title,
      status: "PROPOSED",
    },
    select: {
      id: true,
    },
  });

  const data = {
    title: suggestion.title,
    summary: suggestion.recommendedAction,
    context: {
      source: "alert-engine",
      fingerprint: suggestion.fingerprint,
      severity: suggestion.severity,
    },
    content: {
      cause: suggestion.probableCause,
      delay: suggestion.recommendedDelay,
      message: suggestion.message,
    },
    priority: alertSeverityToPriority(suggestion.severity),
    status: "PROPOSED" as const,
    generatedAt: new Date(),
  };

  if (existingRecommendation) {
    await prisma.aiRecommendation.update({
      where: {
        id: existingRecommendation.id,
      },
      data,
    });
    return;
  }

  await prisma.aiRecommendation.create({
    data: {
      userId,
      aquariumId,
      ...data,
    },
  });
}

export async function analyzeAquariumForUser(
  userId: string,
  aquariumId: string
): Promise<AquariumAlertAnalysisResult> {
  const aquarium = await prisma.aquarium.findFirst({
    where: {
      id: aquariumId,
      userId,
      isArchived: false,
    },
    select: {
      id: true,
      name: true,
      startedAt: true,
      volumeLiters: true,
      currentTemperatureC: true,
      targetTemperatureC: true,
      lightingHoursPerDay: true,
      filtrationType: true,
    },
  });

  if (!aquarium) {
    return {
      created: 0,
      updated: 0,
      activeCount: 0,
      recommendationCount: 0,
    };
  }

  const [
    latestWater,
    fishEntries,
    plantAggregate,
    maintenanceLogs,
    feedingLogs,
  ] = await Promise.all([
    prisma.waterParameter.findFirst({
      where: {
        userId,
        aquariumId,
      },
      orderBy: {
        measuredAt: "desc",
      },
      select: {
        measuredAt: true,
        temperatureC: true,
        ph: true,
        kh: true,
        ammoniaMgL: true,
        nitriteMgL: true,
        nitrateMgL: true,
      },
    }),
    prisma.aquariumFish.findMany({
      where: {
        userId,
        aquariumId,
        status: "ACTIVE",
      },
      select: {
        quantity: true,
        species: {
          select: {
            commonName: true,
            minTemperatureC: true,
            maxTemperatureC: true,
            minPh: true,
            maxPh: true,
          },
        },
      },
    }),
    prisma.aquariumPlant.aggregate({
      where: {
        userId,
        aquariumId,
        status: {
          not: "REMOVED",
        },
      },
      _sum: {
        quantity: true,
      },
    }),
    prisma.maintenanceLog.findMany({
      where: {
        userId,
        aquariumId,
      },
      orderBy: {
        performedAt: "desc",
      },
      select: {
        type: true,
        performedAt: true,
      },
      take: 80,
    }),
    prisma.feedingLog.findMany({
      where: {
        userId,
        aquariumId,
        fedAt: {
          gte: new Date(Date.now() - 24 * 60 * 60 * 1000),
        },
      },
      select: {
        id: true,
      },
    }),
  ]);

  const fishCount = fishEntries.reduce((sum, entry) => sum + entry.quantity, 0);
  const plantCount = plantAggregate._sum.quantity ?? 0;
  const ageDays = daysSince(aquarium.startedAt);
  const isYoungTank = ageDays !== null && ageDays < 42;
  const nitrate = decimalToNumber(latestWater?.nitrateMgL);
  const nitrite = decimalToNumber(latestWater?.nitriteMgL);
  const ammonia = decimalToNumber(latestWater?.ammoniaMgL);
  const ph = decimalToNumber(latestWater?.ph);
  const kh = latestWater?.kh ?? null;
  const waterTemperature =
    decimalToNumber(latestWater?.temperatureC) ??
    decimalToNumber(aquarium.currentTemperatureC) ??
    decimalToNumber(aquarium.targetTemperatureC);
  const lightingHours = decimalToNumber(aquarium.lightingHoursPerDay);
  const waterAgeDays = daysSince(latestWater?.measuredAt);
  const lastWaterChange = latestDateByType(maintenanceLogs, "WATER_CHANGE");
  const lastFilterCleaning =
    latestDateByType(maintenanceLogs, "FILTER_CLEANING") ??
    latestDateByType(maintenanceLogs, "FILTER_MEDIA_RINSE");
  const waterChangeAgeDays = daysSince(lastWaterChange);
  const filterCleaningAgeDays = daysSince(lastFilterCleaning);
  const suggestions: AlertSuggestion[] = [];

  if (nitrite !== null && nitrite > 0) {
    suggestions.push({
      fingerprint: "water:nitrite-positive",
      type: "WATER_PARAMETER",
      severity: "CRITICAL",
      title: "Nitrites detectes",
      message: `NO2 mesure a ${nitrite} mg/L. Les nitrites doivent rester a 0 en aquarium.`,
      probableCause: "Cycle azote instable, suralimentation, filtre perturbe ou bac trop recent.",
      recommendedAction: "Faire un changement d'eau, verifier le filtre, reduire le nourrissage et retester rapidement.",
      recommendedDelay: "Immediat",
    });
  }

  if (ammonia !== null && ammonia > 0) {
    suggestions.push({
      fingerprint: "water:ammonia-positive",
      type: "WATER_PARAMETER",
      severity: "CRITICAL",
      title: "Ammoniaque detectee",
      message: `NH3/NH4 mesure a ${ammonia} mg/L. Cette valeur doit rester a 0.`,
      probableCause: "Pollution organique, bac non cycle, filtre insuffisant ou surpopulation.",
      recommendedAction: "Changer une partie de l'eau, proteger la filtration biologique et tester NO2/NH3.",
      recommendedDelay: "Immediat",
    });
  }

  if (nitrate !== null && nitrate > 50) {
    suggestions.push({
      fingerprint: "water:nitrate-important",
      type: "WATER_PARAMETER",
      severity: "IMPORTANT",
      title: "Nitrates tres eleves",
      message: `NO3 mesure a ${nitrate} mg/L, au-dessus du seuil de 50 mg/L.`,
      probableCause: "Changements d'eau trop espaces, population elevee, pollution organique ou plantes insuffisantes.",
      recommendedAction: "Planifier un changement d'eau rapproche et verifier la frequence de nourrissage.",
      recommendedDelay: "Sous 24 a 48 h",
      reminder: {
        type: "WATER_CHANGE",
        title: "Changement d'eau apres NO3 eleves",
        description: "NO3 au-dessus de 50 mg/L : changement d'eau recommande.",
        dueInDays: 1,
        repeatEveryDays: 7,
      },
    });
  } else if (nitrate !== null && nitrate > 25) {
    suggestions.push({
      fingerprint: "water:nitrate-attention",
      type: "WATER_PARAMETER",
      severity: "ATTENTION",
      title: "Nitrates a surveiller",
      message: `NO3 mesure a ${nitrate} mg/L, au-dessus du seuil de vigilance de 25 mg/L.`,
      probableCause: "Accumulation progressive de nitrates ou entretien a ajuster.",
      recommendedAction: "Surveiller l'evolution, renforcer les changements d'eau et limiter les exces de nourriture.",
      recommendedDelay: "Cette semaine",
    });
  }

  const phProblem = getRangeProblem(
    ph,
    fishEntries.map((entry) => ({
      min: decimalToNumber(entry.species.minPh),
      max: decimalToNumber(entry.species.maxPh),
      name: entry.species.commonName,
    }))
  );

  if (phProblem) {
    suggestions.push({
      fingerprint: "fish:ph-out-of-range",
      type: "FISH_HEALTH",
      severity: "IMPORTANT",
      title: "pH hors plage pour certains poissons",
      message: `Le pH actuel est ${ph}. Il est ${phProblem.direction} pour : ${phProblem.impacted}.`,
      probableCause: "Parametres d'eau inadaptes a une partie de la population.",
      recommendedAction: "Verifier les besoins des especes et corriger progressivement le pH.",
      recommendedDelay: "Sous 24 a 48 h",
    });
  }

  const temperatureProblem = getRangeProblem(
    waterTemperature,
    fishEntries.map((entry) => ({
      min: decimalToNumber(entry.species.minTemperatureC),
      max: decimalToNumber(entry.species.maxTemperatureC),
      name: entry.species.commonName,
    }))
  );

  if (temperatureProblem) {
    suggestions.push({
      fingerprint: "fish:temperature-out-of-range",
      type: "FISH_HEALTH",
      severity: "IMPORTANT",
      title: "Temperature hors plage",
      message: `La temperature actuelle est ${waterTemperature} C. Elle est ${temperatureProblem.direction} pour : ${temperatureProblem.impacted}.`,
      probableCause: "Chauffage, piece ou consigne mal adaptes a la population.",
      recommendedAction: "Verifier chauffage, thermometre et besoins des especes avant correction progressive.",
      recommendedDelay: "Aujourd'hui",
    });
  }

  if (kh !== null && kh < 3) {
    suggestions.push({
      fingerprint: "water:kh-low",
      type: "WATER_PARAMETER",
      severity: "ATTENTION",
      title: "KH bas",
      message: `KH mesure a ${kh}. Un KH trop bas peut rendre le pH instable.`,
      probableCause: "Eau tres douce, consommation de carbonates ou changements d'eau inadaptes.",
      recommendedAction: "Surveiller le pH et ajuster doucement la mineralisation si necessaire.",
      recommendedDelay: "Cette semaine",
    });
  }

  if (waterAgeDays === null || waterAgeDays > 7) {
    suggestions.push({
      fingerprint: "water:test-overdue",
      type: "MAINTENANCE_OVERDUE",
      severity: waterAgeDays === null ? "ATTENTION" : "IMPORTANT",
      title: "Test d'eau a faire",
      message: waterAgeDays === null
        ? "Aucun test d'eau n'est encore enregistre pour cet aquarium."
        : `Aucun test d'eau depuis ${waterAgeDays} jours.`,
      probableCause: "Suivi des parametres trop espace.",
      recommendedAction: "Mesurer temperature, pH, KH, NO2, NO3 et NH3/NH4.",
      recommendedDelay: "Aujourd'hui",
      reminder: {
        type: "WATER_TEST",
        title: "Tester les parametres d'eau",
        description: "Aucun test recent : controle complet recommande.",
        dueInDays: 0,
        repeatEveryDays: 7,
      },
    });
  }

  if (waterChangeAgeDays === null || waterChangeAgeDays > 14) {
    suggestions.push({
      fingerprint: "maintenance:water-change-overdue",
      type: "MAINTENANCE_OVERDUE",
      severity: waterChangeAgeDays === null ? "ATTENTION" : "IMPORTANT",
      title: "Changement d'eau a planifier",
      message: waterChangeAgeDays === null
        ? "Aucun changement d'eau n'est encore enregistre."
        : `Dernier changement d'eau il y a ${waterChangeAgeDays} jours.`,
      probableCause: "Entretien espace ou historique incomplet.",
      recommendedAction: "Planifier un changement d'eau adapte au volume et aux nitrates.",
      recommendedDelay: "Sous 48 h",
      reminder: {
        type: "WATER_CHANGE",
        title: "Changement d'eau recommande",
        description: "Changement d'eau non fait depuis plus de 14 jours.",
        dueInDays: 1,
        repeatEveryDays: 14,
      },
    });
  }

  if (isYoungTank) {
    suggestions.push({
      fingerprint: "system:young-tank",
      type: "SYSTEM",
      severity: "INFORMATION",
      title: "Bac jeune sous surveillance",
      message: `Aquarium lance depuis ${ageDays ?? 0} jours, soit moins de 6 semaines.`,
      probableCause: "Cycle biologique en cours de stabilisation.",
      recommendedAction: "Tester NO2/NH3 tous les 2 a 3 jours et introduire le vivant progressivement.",
      recommendedDelay: "Pendant les 6 premieres semaines",
    });
  }

  if (lightingHours !== null && lightingHours > 10) {
    suggestions.push({
      fingerprint: "lighting:too-long",
      type: "PLANT_HEALTH",
      severity: "ATTENTION",
      title: "Duree d'eclairage elevee",
      message: `Eclairage configure a ${lightingHours} h/jour, au-dessus de 10 h.`,
      probableCause: "Photoperiode longue pouvant favoriser les algues.",
      recommendedAction: "Surveiller les algues et envisager une reduction progressive de la duree.",
      recommendedDelay: "Cette semaine",
    });
  }

  if (feedingLogs.length >= 4) {
    suggestions.push({
      fingerprint: "feeding:too-frequent",
      type: "FEEDING",
      severity: "ATTENTION",
      title: "Nourrissage tres frequent",
      message: `${feedingLogs.length} nourrissages enregistres sur les dernieres 24 h.`,
      probableCause: "Risque de suralimentation ou de pollution organique.",
      recommendedAction: "Reduire les quantites, retirer les restes et surveiller NO2/NH3.",
      recommendedDelay: "Aujourd'hui",
    });
  }

  if (filterCleaningAgeDays === null || filterCleaningAgeDays > 45) {
    suggestions.push({
      fingerprint: "equipment:filter-cleaning-overdue",
      type: "EQUIPMENT",
      severity: "ATTENTION",
      title: "Filtre a verifier",
      message: filterCleaningAgeDays === null
        ? "Aucun nettoyage ou rincage de filtre n'est enregistre."
        : `Dernier entretien filtre il y a ${filterCleaningAgeDays} jours.`,
      probableCause: "Entretien filtre espace ou historique incomplet.",
      recommendedAction: "Verifier le debit et rincer les masses mecaniques avec de l'eau de l'aquarium si necessaire.",
      recommendedDelay: "Cette semaine",
      reminder: {
        type: "FILTER_CLEANING",
        title: "Verifier le filtre",
        description: "Filtre non nettoye depuis longtemps.",
        dueInDays: 3,
        repeatEveryDays: 30,
      },
    });
  }

  if (fishCount > 0 && plantCount === 0 && nitrate !== null && nitrate > 25) {
    suggestions.push({
      fingerprint: "balance:no-plants-nitrate",
      type: "CUSTOM",
      severity: "INFORMATION",
      title: "Equilibre plantes/nitrates",
      message: "Le bac contient des poissons, peu ou pas de plantes, et les nitrates montent.",
      probableCause: "Absence de consommation vegetale significative des nitrates.",
      recommendedAction: "Envisager des plantes faciles a pousse rapide ou renforcer les changements d'eau.",
      recommendedDelay: "A la prochaine evolution du bac",
    });
  }

  let created = 0;
  let updated = 0;

  for (const suggestion of suggestions) {
    const result = await upsertAlertSuggestion(userId, aquariumId, suggestion);
    await upsertRecommendation(userId, aquariumId, suggestion);

    if (suggestion.reminder) {
      await ensureReminder(userId, aquariumId, suggestion.reminder);
    }

    if (result === "created") {
      created += 1;
    } else {
      updated += 1;
    }
  }

  const activeCount = await prisma.alert.count({
    where: {
      userId,
      aquariumId,
      status: {
        in: ["OPEN", "ACKNOWLEDGED"],
      },
    },
  });

  return {
    created,
    updated,
    activeCount,
    recommendationCount: suggestions.length,
  };
}

export async function analyzeAquarium(aquariumId: string) {
  const user = await requireUser();
  return analyzeAquariumForUser(user.id, aquariumId);
}

export async function getAquariumAlerts(userId: string, aquariumId: string) {
  const alerts = await prisma.alert.findMany({
    where: {
      userId,
      aquariumId,
      aquarium: {
        userId,
        isArchived: false,
      },
    },
    orderBy: [{ status: "asc" }, { severity: "desc" }, { triggeredAt: "desc" }],
    select: alertSelect,
  });

  return alerts.map(toAlertEntry);
}
