import { requireUser } from "@/lib/auth/session";
import { prisma } from "@/lib/prisma";
import {
  getReminderPriorityLabel,
  getReminderTypeLabel,
  type ReminderPriorityValue,
  type ReminderTypeValue,
} from "@/rules/reminder";

type DecimalLike = {
  toString(): string;
};

type ReminderSuggestion = {
  type: ReminderTypeValue;
  title: string;
  description: string;
  dueAt: Date;
  repeatEveryDays: number;
  priority: ReminderPriorityValue;
};

type RawReminder = {
  id: string;
  type: string;
  title: string;
  description: string | null;
  dueAt: Date;
  repeatEveryDays: number | null;
  priority: string;
  status: string;
  isAutoGenerated: boolean;
  isAutoEnabled: boolean;
  completedAt: Date | null;
  createdAt: Date;
};

export type ReminderEntry = {
  id: string;
  type: string;
  typeLabel: string;
  title: string;
  description: string;
  dueAt: string;
  dueAtLabel: string;
  repeatEveryDays: number | null;
  priority: string;
  priorityLabel: string;
  status: string;
  isAutoGenerated: boolean;
  isAutoEnabled: boolean;
};

export type ReminderBoard = {
  today: ReminderEntry[];
  overdue: ReminderEntry[];
  upcoming: ReminderEntry[];
  disabled: ReminderEntry[];
};

export type SmartReminderGenerationResult = {
  created: number;
  updated: number;
  skipped: number;
};

const reminderSelect = {
  id: true,
  type: true,
  title: true,
  description: true,
  dueAt: true,
  repeatEveryDays: true,
  priority: true,
  status: true,
  isAutoGenerated: true,
  isAutoEnabled: true,
  completedAt: true,
  createdAt: true,
} as const;

const priorityRank: Record<string, number> = {
  LOW: 1,
  MEDIUM: 2,
  HIGH: 3,
  CRITICAL: 4,
};

function decimalToNumber(value: DecimalLike | null | undefined) {
  if (!value) {
    return null;
  }

  const numberValue = Number(value.toString());

  return Number.isFinite(numberValue) ? numberValue : null;
}

function startOfToday() {
  const date = new Date();
  date.setHours(0, 0, 0, 0);
  return date;
}

function endOfToday() {
  const date = startOfToday();
  date.setHours(23, 59, 59, 999);
  return date;
}

function addDays(date: Date, days: number) {
  const nextDate = new Date(date);
  nextDate.setDate(nextDate.getDate() + days);
  return nextDate;
}

function dueFrom(lastDate: Date | null | undefined, intervalDays: number) {
  const base = lastDate ? addDays(lastDate, intervalDays) : new Date();
  base.setHours(9, 0, 0, 0);
  return base;
}

function daysSince(date: Date | null | undefined) {
  if (!date) {
    return null;
  }

  return Math.floor((Date.now() - date.getTime()) / (24 * 60 * 60 * 1000));
}

function maxPriority(
  current: string,
  next: ReminderPriorityValue
): ReminderPriorityValue {
  return priorityRank[current] > priorityRank[next] ? (current as ReminderPriorityValue) : next;
}

function priorityWithOverduePressure(
  priority: ReminderPriorityValue,
  overdueCount: number
): ReminderPriorityValue {
  if (overdueCount >= 4) {
    return maxPriority(priority, "CRITICAL");
  }

  if (overdueCount > 0) {
    return maxPriority(priority, "HIGH");
  }

  return priority;
}

function toReminderEntry(reminder: RawReminder): ReminderEntry {
  return {
    id: reminder.id,
    type: reminder.type,
    typeLabel: getReminderTypeLabel(reminder.type),
    title: reminder.title,
    description: reminder.description ?? "",
    dueAt: reminder.dueAt.toISOString(),
    dueAtLabel: reminder.dueAt.toLocaleDateString("fr-FR", {
      dateStyle: "medium",
    }),
    repeatEveryDays: reminder.repeatEveryDays,
    priority: reminder.priority,
    priorityLabel: getReminderPriorityLabel(reminder.priority),
    status: reminder.status,
    isAutoGenerated: reminder.isAutoGenerated,
    isAutoEnabled: reminder.isAutoEnabled,
  };
}

function latestDateByType(
  logs: { type: string; performedAt: Date }[],
  type: string
) {
  return logs.find((log) => log.type === type)?.performedAt ?? null;
}

async function raiseOverdueReminderPriorities(userId: string, aquariumId: string) {
  const overdueReminders = await prisma.reminder.findMany({
    where: {
      userId,
      aquariumId,
      status: "PENDING",
      dueAt: {
        lt: startOfToday(),
      },
      aquarium: {
        userId,
        isArchived: false,
      },
    },
    select: {
      id: true,
      priority: true,
      dueAt: true,
    },
  });

  await Promise.all(
    overdueReminders.map((reminder) => {
      const overdueDays = daysSince(reminder.dueAt) ?? 0;
      const nextPriority = overdueDays >= 7 ? "CRITICAL" : "HIGH";

      if (priorityRank[reminder.priority] >= priorityRank[nextPriority]) {
        return Promise.resolve();
      }

      return prisma.reminder.update({
        where: {
          id: reminder.id,
        },
        data: {
          priority: nextPriority,
        },
      });
    })
  );

  return overdueReminders.length;
}

export async function generateSmartRemindersForUser(
  userId: string,
  aquariumId: string
): Promise<SmartReminderGenerationResult> {
  const aquarium = await prisma.aquarium.findFirst({
    where: {
      id: aquariumId,
      userId,
      isArchived: false,
    },
    select: {
      id: true,
      type: true,
      volumeLiters: true,
      startedAt: true,
      hasCo2: true,
      fertilizer: true,
      lightingHoursPerDay: true,
      currentTemperatureC: true,
      targetTemperatureC: true,
      heaterType: true,
    },
  });

  if (!aquarium) {
    return {
      created: 0,
      updated: 0,
      skipped: 0,
    };
  }

  const [
    fishAggregate,
    plantAggregate,
    latestWater,
    latestFeeding,
    maintenanceLogs,
  ] = await Promise.all([
    prisma.aquariumFish.aggregate({
      where: {
        userId,
        aquariumId,
        status: "ACTIVE",
      },
      _sum: {
        quantity: true,
      },
    }),
    prisma.aquariumPlant.aggregate({
      where: {
        userId,
        aquariumId,
        status: {
          not: "REMOVED",
        },
      },
      _sum: {
        quantity: true,
      },
    }),
    prisma.waterParameter.findFirst({
      where: {
        userId,
        aquariumId,
      },
      orderBy: {
        measuredAt: "desc",
      },
      select: {
        measuredAt: true,
        temperatureC: true,
        nitriteMgL: true,
        nitrateMgL: true,
        ammoniaMgL: true,
      },
    }),
    prisma.feedingLog.findFirst({
      where: {
        userId,
        aquariumId,
      },
      orderBy: {
        fedAt: "desc",
      },
      select: {
        fedAt: true,
      },
    }),
    prisma.maintenanceLog.findMany({
      where: {
        userId,
        aquariumId,
      },
      orderBy: {
        performedAt: "desc",
      },
      select: {
        type: true,
        performedAt: true,
      },
      take: 80,
    }),
  ]);

  const overdueCount = await raiseOverdueReminderPriorities(userId, aquariumId);
  const fishCount = fishAggregate._sum.quantity ?? 0;
  const plantCount = plantAggregate._sum.quantity ?? 0;
  const volumeLiters = decimalToNumber(aquarium.volumeLiters);
  const ageDays = daysSince(aquarium.startedAt);
  const isYoungTank = ageDays !== null && ageDays < 42;
  const nitrateValue = decimalToNumber(latestWater?.nitrateMgL);
  const nitriteValue = decimalToNumber(latestWater?.nitriteMgL);
  const ammoniaValue = decimalToNumber(latestWater?.ammoniaMgL);
  const hasNitrogenRisk =
    (nitriteValue !== null && nitriteValue > 0) ||
    (ammoniaValue !== null && ammoniaValue > 0);
  const hasHighNitrate = nitrateValue !== null && nitrateValue >= 40;
  const hasDensePopulation =
    volumeLiters !== null ? fishCount > Math.max(6, volumeLiters / 8) : fishCount >= 20;
  const isPlantedTank = plantCount > 0 || aquarium.type === "PLANTED";
  const hasFertilizer = Boolean(aquarium.fertilizer?.trim());
  const lightingHours = decimalToNumber(aquarium.lightingHoursPerDay);

  const waterTestInterval = isYoungTank ? (hasNitrogenRisk ? 2 : 3) : 7;
  const waterChangeInterval =
    hasHighNitrate || hasDensePopulation ? 7 : volumeLiters && volumeLiters < 50 ? 10 : 14;
  const substrateInterval = hasDensePopulation ? 14 : 21;

  const suggestions: ReminderSuggestion[] = [
    {
      type: "WATER_TEST",
      title: isYoungTank
        ? "Tester NO2/NH3 du bac jeune"
        : "Tester les parametres d'eau",
      description: isYoungTank
        ? "Bac de moins de 6 semaines : suivi rapproche des nitrites et de l'ammoniaque."
        : "Bac stable : controle hebdomadaire des parametres principaux.",
      dueAt: dueFrom(latestWater?.measuredAt, waterTestInterval),
      repeatEveryDays: waterTestInterval,
      priority: isYoungTank || hasNitrogenRisk ? "HIGH" : "MEDIUM",
    },
    {
      type: "WATER_CHANGE",
      title: "Planifier un changement d'eau",
      description: hasHighNitrate
        ? "NO3 eleve : rapprocher le prochain changement d'eau."
        : hasDensePopulation
          ? "Population elevee : maintenir un rythme de changement d'eau plus court."
          : "Rythme d'entretien regulier pour stabiliser le bac.",
      dueAt: dueFrom(latestDateByType(maintenanceLogs, "WATER_CHANGE"), waterChangeInterval),
      repeatEveryDays: waterChangeInterval,
      priority: hasHighNitrate ? "HIGH" : "MEDIUM",
    },
    {
      type: "FEEDING",
      title: "Nourrir les poissons",
      description: "Rappel quotidien de nourrissage, a ajuster selon la population.",
      dueAt: dueFrom(latestFeeding?.fedAt, 1),
      repeatEveryDays: 1,
      priority: "MEDIUM",
    },
    {
      type: "GLASS_CLEANING",
      title: "Nettoyer les vitres",
      description: "Evite l'accumulation d'algues et garde une bonne visibilite.",
      dueAt: dueFrom(latestDateByType(maintenanceLogs, "GLASS_CLEANING"), 14),
      repeatEveryDays: 14,
      priority: "LOW",
    },
    {
      type: "FILTER_CLEANING",
      title: "Verifier et nettoyer le filtre",
      description: "Controle le debit et nettoie le filtre sans steriliser les masses biologiques.",
      dueAt: dueFrom(latestDateByType(maintenanceLogs, "FILTER_CLEANING"), 30),
      repeatEveryDays: 30,
      priority: "MEDIUM",
    },
    {
      type: "SUBSTRATE_SIPHONING",
      title: "Siphonner le sol",
      description: "Retire les dechets accumules, surtout avec une population dense.",
      dueAt: dueFrom(
        latestDateByType(maintenanceLogs, "SUBSTRATE_SIPHONING"),
        substrateInterval
      ),
      repeatEveryDays: substrateInterval,
      priority: hasDensePopulation ? "MEDIUM" : "LOW",
    },
    {
      type: "TEMPERATURE_CHECK",
      title: "Verifier la temperature",
      description: "Controle rapide de la temperature et de sa stabilite.",
      dueAt: dueFrom(null, 2),
      repeatEveryDays: 2,
      priority: "MEDIUM",
    },
    {
      type: "HEATER_CHECK",
      title: "Verifier le chauffage",
      description: aquarium.heaterType
        ? "Controle du chauffage et de la coherence avec la temperature cible."
        : "Verifie si un chauffage est necessaire selon la population.",
      dueAt: dueFrom(latestDateByType(maintenanceLogs, "HEATER_CHECK"), 30),
      repeatEveryDays: 30,
      priority: "LOW",
    },
    {
      type: "LIGHTING_CHECK",
      title: "Verifier l'eclairage",
      description: "Controle la duree, la programmation et l'etat de l'eclairage.",
      dueAt: dueFrom(latestDateByType(maintenanceLogs, "LIGHTING_CHECK"), 30),
      repeatEveryDays: 30,
      priority: "LOW",
    },
    {
      type: "FISH_VISUAL_CHECK",
      title: "Controle visuel des poissons",
      description: "Observe respiration, nage, appetit et signes de stress.",
      dueAt: dueFrom(null, 1),
      repeatEveryDays: 1,
      priority: "MEDIUM",
    },
  ];

  if (isPlantedTank) {
    suggestions.push(
      {
        type: "PLANT_TRIMMING",
        title: "Tailler les plantes",
        description: "Bac plante : taille reguliere pour eviter l'ombrage et densifier les massifs.",
        dueAt: dueFrom(latestDateByType(maintenanceLogs, "PLANT_TRIMMING"), 21),
        repeatEveryDays: 21,
        priority: "LOW",
      },
      {
        type: "FERTILIZATION",
        title: "Ajouter ou verifier l'engrais",
        description: hasFertilizer
          ? "Engrais renseigne : maintenir une routine stable."
          : "Bac plante : verifier si une fertilisation adaptee est necessaire.",
        dueAt: dueFrom(latestDateByType(maintenanceLogs, "FERTILIZATION"), 7),
        repeatEveryDays: 7,
        priority: hasFertilizer ? "MEDIUM" : "LOW",
      }
    );
  }

  if (aquarium.hasCo2) {
    suggestions.push({
      type: "CO2_CHECK",
      title: "Controler le CO2",
      description: "CO2 present : verifier diffusion, securite et comportement des poissons.",
      dueAt: dueFrom(null, 1),
      repeatEveryDays: 1,
      priority: "HIGH",
    });
  }

  if (lightingHours !== null && lightingHours > 10) {
    suggestions.push({
      type: "ALGAE_CHECK",
      title: "Controler les algues",
      description: "Eclairage superieur a 10 h/jour : surveiller les algues et l'equilibre du bac.",
      dueAt: dueFrom(null, 3),
      repeatEveryDays: 3,
      priority: "MEDIUM",
    });
  }

  const existingAutoReminders = await prisma.reminder.findMany({
    where: {
      userId,
      aquariumId,
      isAutoGenerated: true,
    },
    select: reminderSelect,
  });

  let created = 0;
  let updated = 0;
  let skipped = 0;

  for (const suggestion of suggestions) {
    const disabledReminder = existingAutoReminders.find(
      (reminder) => reminder.type === suggestion.type && !reminder.isAutoEnabled
    );

    if (disabledReminder) {
      skipped += 1;
      continue;
    }

    const activeReminder = existingAutoReminders.find(
      (reminder) =>
        reminder.type === suggestion.type &&
        reminder.isAutoEnabled &&
        (reminder.status === "PENDING" || reminder.status === "SNOOZED")
    );
    const nextPriority = priorityWithOverduePressure(
      suggestion.priority,
      overdueCount
    );

    if (activeReminder) {
      const shouldMoveEarlier =
        activeReminder.dueAt > suggestion.dueAt &&
        priorityRank[nextPriority] >= priorityRank.HIGH;

      await prisma.reminder.update({
        where: {
          id: activeReminder.id,
        },
        data: {
          title: suggestion.title,
          description: suggestion.description,
          priority: maxPriority(activeReminder.priority, nextPriority),
          repeatEveryDays:
            activeReminder.repeatEveryDays ?? suggestion.repeatEveryDays,
          dueAt: shouldMoveEarlier ? suggestion.dueAt : activeReminder.dueAt,
        },
      });
      updated += 1;
      continue;
    }

    await prisma.reminder.create({
      data: {
        userId,
        aquariumId,
        type: suggestion.type,
        title: suggestion.title,
        description: suggestion.description,
        dueAt: suggestion.dueAt,
        repeatEveryDays: suggestion.repeatEveryDays,
        priority: nextPriority,
        status: "PENDING",
        isAutoGenerated: true,
        isAutoEnabled: true,
      },
    });
    created += 1;
  }

  return {
    created,
    updated,
    skipped,
  };
}

export async function generateSmartReminders(aquariumId: string) {
  const user = await requireUser();
  return generateSmartRemindersForUser(user.id, aquariumId);
}

export async function getReminderBoard(
  userId: string,
  aquariumId: string
): Promise<ReminderBoard> {
  const reminders = await prisma.reminder.findMany({
    where: {
      userId,
      aquariumId,
      aquarium: {
        userId,
        isArchived: false,
      },
    },
    orderBy: [{ dueAt: "asc" }, { priority: "desc" }],
    select: reminderSelect,
  });
  const start = startOfToday();
  const end = endOfToday();
  const board: ReminderBoard = {
    today: [],
    overdue: [],
    upcoming: [],
    disabled: [],
  };

  for (const reminder of reminders.map(toReminderEntry)) {
    const dueAt = new Date(reminder.dueAt);
    const isDisabled =
      reminder.status === "CANCELLED" ||
      (reminder.isAutoGenerated && !reminder.isAutoEnabled);

    if (isDisabled) {
      board.disabled.push(reminder);
      continue;
    }

    if (reminder.status !== "PENDING" && reminder.status !== "SNOOZED") {
      continue;
    }

    if (dueAt < start) {
      board.overdue.push(reminder);
    } else if (dueAt <= end) {
      board.today.push(reminder);
    } else {
      board.upcoming.push(reminder);
    }
  }

  return board;
}
