"use server";

import { revalidatePath } from "next/cache";
import { z } from "zod";

import { requireUser } from "@/lib/auth/session";
import { prisma } from "@/lib/prisma";
import {
  manualReminderFormSchema,
  reminderFrequencySchema,
  type ManualReminderFormValues,
} from "@/rules/reminder";
import { generateSmartReminders } from "@/services/reminder-service";

export type ReminderActionState = {
  message?: string;
  fieldErrors?: Record<string, string>;
};

function formatFieldErrors(error: z.ZodError) {
  const fieldErrors: Record<string, string> = {};

  for (const issue of error.issues) {
    const field = issue.path[0];

    if (typeof field === "string" && !fieldErrors[field]) {
      fieldErrors[field] = issue.message;
    }
  }

  return fieldErrors;
}

function emptyToUndefined(value: string) {
  const trimmedValue = value.trim();

  return trimmedValue.length > 0 ? trimmedValue : undefined;
}

function dueDateToDateTime(value: string) {
  const dueAt = new Date(`${value}T09:00:00.000`);
  return dueAt;
}

function addDays(date: Date, days: number) {
  const nextDate = new Date(date);
  nextDate.setDate(nextDate.getDate() + days);
  return nextDate;
}

function getNextDueAt(dueAt: Date, repeatEveryDays: number) {
  let nextDueAt = addDays(dueAt, repeatEveryDays);
  const now = new Date();

  while (nextDueAt <= now) {
    nextDueAt = addDays(nextDueAt, repeatEveryDays);
  }

  return nextDueAt;
}

function toManualReminderData(values: ManualReminderFormValues) {
  return {
    type: values.type,
    title: values.title,
    description: emptyToUndefined(values.description),
    dueAt: dueDateToDateTime(values.dueDate),
    priority: values.priority,
    repeatEveryDays: values.repeatEveryDays
      ? Number(values.repeatEveryDays)
      : undefined,
  };
}

async function getUserReminder(userId: string, reminderId: string) {
  return prisma.reminder.findFirst({
    where: {
      id: reminderId,
      userId,
      aquarium: {
        userId,
        isArchived: false,
      },
    },
    select: {
      id: true,
      userId: true,
      aquariumId: true,
      type: true,
      title: true,
      description: true,
      dueAt: true,
      repeatEveryDays: true,
      priority: true,
      isAutoGenerated: true,
      isAutoEnabled: true,
    },
  });
}

async function createNextReminderOccurrence(reminder: Awaited<ReturnType<typeof getUserReminder>>) {
  if (!reminder?.repeatEveryDays) {
    return;
  }

  await prisma.reminder.create({
    data: {
      userId: reminder.userId,
      aquariumId: reminder.aquariumId,
      type: reminder.type,
      title: reminder.title,
      description: reminder.description,
      dueAt: getNextDueAt(reminder.dueAt, reminder.repeatEveryDays),
      repeatEveryDays: reminder.repeatEveryDays,
      priority: reminder.priority,
      status: "PENDING",
      isAutoGenerated: reminder.isAutoGenerated,
      isAutoEnabled: reminder.isAutoEnabled,
    },
  });
}

export async function createManualReminderAction(
  aquariumId: string,
  input: unknown
): Promise<ReminderActionState> {
  const user = await requireUser();
  const parsedInput = manualReminderFormSchema.safeParse(input);

  if (!parsedInput.success) {
    return {
      message: "Verifie les informations du rappel.",
      fieldErrors: formatFieldErrors(parsedInput.error),
    };
  }

  const aquarium = await prisma.aquarium.findFirst({
    where: {
      id: aquariumId,
      userId: user.id,
      isArchived: false,
    },
    select: {
      id: true,
    },
  });

  if (!aquarium) {
    return {
      message: "Aquarium introuvable ou inaccessible.",
    };
  }

  await prisma.reminder.create({
    data: {
      userId: user.id,
      aquariumId: aquarium.id,
      ...toManualReminderData(parsedInput.data),
      status: "PENDING",
      isAutoGenerated: false,
      isAutoEnabled: true,
    },
  });

  revalidatePath(`/aquariums/${aquarium.id}/reminders`);
  return {
    message: "Rappel manuel cree.",
  };
}

export async function completeReminderAction(reminderId: string) {
  const user = await requireUser();
  const reminder = await getUserReminder(user.id, reminderId);

  if (!reminder) {
    return;
  }

  await prisma.reminder.update({
    where: {
      id: reminder.id,
    },
    data: {
      status: "COMPLETED",
      completedAt: new Date(),
    },
  });

  if (reminder.isAutoEnabled) {
    await createNextReminderOccurrence(reminder);
  }

  revalidatePath(`/aquariums/${reminder.aquariumId}/reminders`);
}

export async function ignoreReminderAction(reminderId: string) {
  const user = await requireUser();
  const reminder = await getUserReminder(user.id, reminderId);

  if (!reminder) {
    return;
  }

  await prisma.reminder.update({
    where: {
      id: reminder.id,
    },
    data: {
      status: "CANCELLED",
    },
  });

  if (reminder.isAutoEnabled) {
    await createNextReminderOccurrence(reminder);
  }

  revalidatePath(`/aquariums/${reminder.aquariumId}/reminders`);
}

export async function disableAutoReminderAction(reminderId: string) {
  const user = await requireUser();
  const reminder = await getUserReminder(user.id, reminderId);

  if (!reminder) {
    return;
  }

  await prisma.reminder.update({
    where: {
      id: reminder.id,
    },
    data: {
      status: "CANCELLED",
      isAutoEnabled: false,
    },
  });

  revalidatePath(`/aquariums/${reminder.aquariumId}/reminders`);
}

export async function updateReminderFrequencyAction(
  reminderId: string,
  formData: FormData
) {
  const user = await requireUser();
  const reminder = await getUserReminder(user.id, reminderId);

  if (!reminder) {
    return;
  }

  const parsedInput = reminderFrequencySchema.safeParse({
    repeatEveryDays: formData.get("repeatEveryDays"),
  });

  if (!parsedInput.success) {
    return;
  }

  const repeatEveryDays = Number(parsedInput.data.repeatEveryDays);

  await prisma.reminder.update({
    where: {
      id: reminder.id,
    },
    data: {
      repeatEveryDays,
      dueAt: getNextDueAt(new Date(), repeatEveryDays),
      status: "PENDING",
    },
  });

  revalidatePath(`/aquariums/${reminder.aquariumId}/reminders`);
}

export async function generateSmartRemindersAction(aquariumId: string) {
  await generateSmartReminders(aquariumId);
  revalidatePath(`/aquariums/${aquariumId}/reminders`);
}
