import Link from "next/link";
import { notFound } from "next/navigation";
import {
  ArrowLeft,
  Bell,
  CalendarClock,
  CheckCircle2,
  PauseCircle,
  RefreshCw,
  SlidersHorizontal,
  XCircle,
} from "lucide-react";

import { ManualReminderForm } from "@/components/reminders/manual-reminder-form";
import { cn } from "@/lib/utils";
import { requireUser } from "@/lib/auth/session";
import { getUserAquariumById } from "@/services/aquarium-service";
import {
  completeReminderAction,
  disableAutoReminderAction,
  generateSmartRemindersAction,
  ignoreReminderAction,
  updateReminderFrequencyAction,
} from "@/services/reminder-actions";
import {
  generateSmartRemindersForUser,
  getReminderBoard,
  type ReminderEntry,
} from "@/services/reminder-service";

export const dynamic = "force-dynamic";

type RemindersPageProps = {
  params: Promise<{
    id: string;
  }>;
};

const priorityStyles: Record<string, string> = {
  LOW: "border-slate-200 bg-slate-50 text-slate-700",
  MEDIUM: "border-cyan-200 bg-cyan-50 text-cyan-800",
  HIGH: "border-amber-200 bg-amber-50 text-amber-800",
  CRITICAL: "border-red-200 bg-red-50 text-red-700",
};

function StatCard({
  label,
  value,
  helper,
}: {
  label: string;
  value: string;
  helper: string;
}) {
  return (
    <article className="aqua-card p-5">
      <p className="text-sm font-medium text-slate-500">{label}</p>
      <p className="mt-2 text-2xl font-semibold text-slate-950">{value}</p>
      <p className="mt-1 text-sm text-slate-500">{helper}</p>
    </article>
  );
}

function ReminderCard({ reminder }: { reminder: ReminderEntry }) {
  const priorityClass =
    priorityStyles[reminder.priority] ?? priorityStyles.MEDIUM;

  return (
    <article className="aqua-card p-5">
      <div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between">
        <div>
          <div className="flex flex-wrap items-center gap-2">
            <span className="rounded-lg bg-cyan-50 px-2 py-1 text-xs font-medium text-cyan-800">
              {reminder.typeLabel}
            </span>
            <span
              className={cn(
                "rounded-lg border px-2 py-1 text-xs font-medium",
                priorityClass
              )}
            >
              {reminder.priorityLabel}
            </span>
            {reminder.isAutoGenerated ? (
              <span className="rounded-lg bg-slate-100 px-2 py-1 text-xs font-medium text-slate-600">
                Auto
              </span>
            ) : (
              <span className="rounded-lg bg-emerald-50 px-2 py-1 text-xs font-medium text-emerald-700">
                Manuel
              </span>
            )}
          </div>
          <h3 className="mt-3 text-lg font-semibold text-slate-950">
            {reminder.title}
          </h3>
          <p className="mt-2 text-sm leading-6 text-slate-600">
            {reminder.description || "Aucune description."}
          </p>
          <p className="mt-3 text-sm font-medium text-slate-700">
            Echeance : {reminder.dueAtLabel}
          </p>
        </div>

        {reminder.status === "PENDING" || reminder.status === "SNOOZED" ? (
          <div className="flex flex-col gap-2 lg:min-w-72">
            <div className="flex flex-wrap gap-2">
              <form action={completeReminderAction.bind(null, reminder.id)}>
                <button
                  type="submit"
                  className="inline-flex h-9 items-center justify-center gap-2 rounded-lg bg-cyan-700 px-3 text-sm font-medium text-white transition-colors hover:bg-cyan-800"
                >
                  <CheckCircle2 className="size-4" aria-hidden="true" />
                  Fait
                </button>
              </form>
              <form action={ignoreReminderAction.bind(null, reminder.id)}>
                <button
                  type="submit"
                  className="inline-flex h-9 items-center justify-center gap-2 rounded-lg border border-slate-200 bg-white px-3 text-sm font-medium text-slate-800 transition-colors hover:bg-slate-50"
                >
                  <XCircle className="size-4" aria-hidden="true" />
                  Ignorer
                </button>
              </form>
              {reminder.isAutoGenerated && reminder.isAutoEnabled ? (
                <form action={disableAutoReminderAction.bind(null, reminder.id)}>
                  <button
                    type="submit"
                    className="inline-flex h-9 items-center justify-center gap-2 rounded-lg border border-amber-200 bg-amber-50 px-3 text-sm font-medium text-amber-800 transition-colors hover:bg-amber-100"
                  >
                    <PauseCircle className="size-4" aria-hidden="true" />
                    Desactiver auto
                  </button>
                </form>
              ) : null}
            </div>
            <form
              action={updateReminderFrequencyAction.bind(null, reminder.id)}
              className="flex items-center gap-2"
            >
              <label className="sr-only" htmlFor={`repeat-${reminder.id}`}>
                Frequence en jours
              </label>
              <input
                id={`repeat-${reminder.id}`}
                name="repeatEveryDays"
                type="number"
                min="1"
                max="365"
                step="1"
                defaultValue={reminder.repeatEveryDays ?? 7}
                className="h-9 w-24 rounded-lg border border-slate-200 bg-white px-3 text-sm outline-none transition-colors focus:border-cyan-500 focus:ring-3 focus:ring-cyan-100"
              />
              <button
                type="submit"
                className="inline-flex h-9 items-center justify-center gap-2 rounded-lg border border-slate-200 bg-white px-3 text-sm font-medium text-slate-800 transition-colors hover:bg-slate-50"
              >
                <SlidersHorizontal className="size-4" aria-hidden="true" />
                Modifier frequence
              </button>
            </form>
          </div>
        ) : null}
      </div>
    </article>
  );
}

function ReminderSection({
  title,
  description,
  reminders,
}: {
  title: string;
  description: string;
  reminders: ReminderEntry[];
}) {
  return (
    <section className="aqua-surface p-6">
      <div className="flex items-center gap-3">
        <span className="rounded-lg bg-cyan-50 p-2 text-cyan-700">
          <CalendarClock className="size-5" aria-hidden="true" />
        </span>
        <div>
          <h2 className="text-xl font-semibold text-slate-950">{title}</h2>
          <p className="mt-1 text-sm text-slate-500">{description}</p>
        </div>
      </div>

      {reminders.length > 0 ? (
        <div className="mt-5 grid gap-4">
          {reminders.map((reminder) => (
            <ReminderCard key={reminder.id} reminder={reminder} />
          ))}
        </div>
      ) : (
        <p className="mt-5 rounded-lg border border-dashed border-slate-200 bg-slate-50 px-4 py-6 text-center text-sm text-slate-600">
          Aucun rappel dans cette section.
        </p>
      )}
    </section>
  );
}

export default async function RemindersPage({ params }: RemindersPageProps) {
  const { id } = await params;
  const user = await requireUser();
  const aquarium = await getUserAquariumById(user.id, id);

  if (!aquarium) {
    notFound();
  }

  await generateSmartRemindersForUser(user.id, aquarium.id);
  const board = await getReminderBoard(user.id, aquarium.id);
  const activeCount =
    board.today.length + board.overdue.length + board.upcoming.length;

  return (
    <div className="mx-auto flex w-full max-w-7xl flex-col gap-6">
      <Link
        href={`/aquariums/${aquarium.id}`}
        className="inline-flex w-fit items-center gap-2 text-sm font-medium text-cyan-700"
      >
        <ArrowLeft className="size-4" aria-hidden="true" />
        Retour au detail
      </Link>

      <section className="flex flex-col gap-4 rounded-lg border border-cyan-100 bg-white p-6 shadow-sm shadow-cyan-950/5 lg:flex-row lg:items-end lg:justify-between">
        <div>
          <p className="text-sm font-medium text-cyan-700">{aquarium.name}</p>
          <h1 className="mt-3 text-3xl font-semibold text-slate-950">
            Rappels intelligents
          </h1>
          <p className="mt-3 max-w-2xl text-base leading-7 text-slate-600">
            Les rappels sont ajustes avec les donnees du bac, l&apos;historique
            et les points de vigilance recents.
          </p>
        </div>
        <form action={generateSmartRemindersAction.bind(null, aquarium.id)}>
          <button
            type="submit"
            className="inline-flex h-10 w-fit items-center justify-center gap-2 rounded-lg bg-cyan-700 px-4 text-sm font-medium text-white transition-colors hover:bg-cyan-800"
          >
            <RefreshCw className="size-4" aria-hidden="true" />
            Regenerer
          </button>
        </form>
      </section>

      <section className="grid gap-4 md:grid-cols-4">
        <StatCard
          label="Aujourd'hui"
          value={board.today.length.toString()}
          helper="rappel(s) a traiter"
        />
        <StatCard
          label="En retard"
          value={board.overdue.length.toString()}
          helper="priorite augmentee"
        />
        <StatCard
          label="A venir"
          value={board.upcoming.length.toString()}
          helper="rappel(s) planifie(s)"
        />
        <StatCard
          label="Actifs"
          value={activeCount.toString()}
          helper={`${board.disabled.length} desactive(s)`}
        />
      </section>

      <ManualReminderForm aquariumId={aquarium.id} />

      <ReminderSection
        title="Rappels du jour"
        description="Actions a effectuer aujourd'hui."
        reminders={board.today}
      />
      <ReminderSection
        title="Rappels en retard"
        description="Les rappels depasses montent automatiquement en priorite."
        reminders={board.overdue}
      />
      <ReminderSection
        title="Rappels a venir"
        description="Planification des prochains entretiens et controles."
        reminders={board.upcoming}
      />
      <section className="aqua-surface p-6">
        <div className="flex items-center gap-3">
          <span className="rounded-lg bg-slate-100 p-2 text-slate-700">
            <Bell className="size-5" aria-hidden="true" />
          </span>
          <div>
            <h2 className="text-xl font-semibold text-slate-950">
              Rappels desactives
            </h2>
            <p className="mt-1 text-sm text-slate-500">
              Rappels ignores ou automatisations mises en pause.
            </p>
          </div>
        </div>
        {board.disabled.length > 0 ? (
          <div className="mt-5 grid gap-4">
            {board.disabled.map((reminder) => (
              <ReminderCard key={reminder.id} reminder={reminder} />
            ))}
          </div>
        ) : (
          <p className="mt-5 rounded-lg border border-dashed border-slate-200 bg-slate-50 px-4 py-6 text-center text-sm text-slate-600">
            Aucun rappel desactive.
          </p>
        )}
      </section>
    </div>
  );
}
